[package]
name = "json-ez"
version = "0.1.0"
authors = ["Alexandre Bouthinon <bouthinon.alexandre@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}